/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GoogleGenAI, Type } from "@google/genai";
import { CivicCategory } from "../src/types";

// Initialize the standard Google GenAI SDK
// Respecting server-side safety constraints: loaded lazy on demand
let aiClient: GoogleGenAI | null = null;

/**
 * Lazy initializer for GoogleGenAI SDK to avoid module-load crashes.
 */
function getAI(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is not defined.");
    }
    aiClient = new GoogleGenAI({ apiKey });
  }
  return aiClient;
}

/**
 * AI Response interface for Triage Agent.
 */
export interface TriageResponse {
  category: CivicCategory;
  severityScore: number;
  confidencePercentage: number;
  recommendedDepartment: string;
  autoGeneratedDescription: string;
}

/**
 * 1. The Triage Agent
 * Analyzes multimodal base64 image strings representing infrastructure issues
 * using Gemini Multimodal Structured Outputs.
 *
 * @param imageBase64 - Base64 encoded string of user uploaded visual issue (with mime prefix stripped or intact)
 * @param mimeType - Image content-type (e.g., 'image/jpeg' or 'image/png')
 * @returns Precise structured AI civic triage analytics
 */
export async function runTriageAgent(
  imageBase64: string,
  mimeType: string,
): Promise<TriageResponse> {
  const ai = getAI();
  const cleanBase64 = imageBase64.replace(/^data:image\/\w+;base64,/, "");

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        {
          inlineData: {
            data: cleanBase64,
            mimeType: mimeType || "image/jpeg",
          },
        },
        'You are the "Triage Agent" of our C.I.V.I.C. platform, an autonomous civic triage specialist. ' +
          "Analyze this user-reported infrastructure issue picture. Assess the visual characteristics of the issue and provide structured diagnostic metrics.",
      ],
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            category: {
              type: Type.STRING,
              description:
                "Type of infrastructure problem. Must fit categorisation: Pothole, Water Leak, Vandalism, Streetlight Out, Waste Issue, or Other.",
              enum: [
                "Pothole",
                "Water Leak",
                "Vandalism",
                "Streetlight Out",
                "Waste Issue",
                "Other",
              ],
            },
            severityScore: {
              type: Type.INTEGER,
              description:
                "Urgency / Severity of issue on a strict 1-10 scale (where 10 is immediate security critical hazard, 1 is cosmetic/local low priority issue).",
            },
            confidencePercentage: {
              type: Type.INTEGER,
              description:
                "Mathematical confidence probability percentage of this categorization based on image resolution & clarity from 1 to 100.",
            },
            recommendedDepartment: {
              type: Type.STRING,
              description:
                "Suggested Municipal agency or public authority best suited to dispatch repairs (e.g. Department of Transportation, Water & Sewage Authority, Department of Public Works, Parks & Forests).",
            },
            autoGeneratedDescription: {
              type: Type.STRING,
              description:
                "Empathetic, clear, and highly detailed human-readable summary detailing the issue visual indicators and severity impacts for civil workers.",
            },
          },
          required: [
            "category",
            "severityScore",
            "confidencePercentage",
            "recommendedDepartment",
            "autoGeneratedDescription",
          ],
        },
      },
    });

    const parsedText = response.text;
    if (!parsedText) {
      throw new Error("Gemini model yielded empty text reply.");
    }

    return JSON.parse(parsedText) as TriageResponse;
  } catch (err: any) {
    console.error("Triage Agent execution failure:", err);
    throw new Error(`AI Triage failed: ${err.message || err}`);
  }
}

/**
 * 2. The Routing Agent
 * Interprets the structural findings output by the Triage Agent.
 * Applies internal service rules depending on confidence status of the model report.
 *
 * @param triageResult - Structured outputs from CRM Triage assessment
 * @returns Status string categorising active routing channel
 */
export function runRoutingAgent(
  triageResult: TriageResponse,
): "Auto-Routed" | "Requires Human Verification" {
  // Rule: If model outputs high confidence (> 85%), route instantly. Otherwise, lock under human verification pipeline.
  if (triageResult.confidencePercentage >= 85) {
    return "Auto-Routed";
  }
  return "Requires Human Verification";
}

/**
 * Calculates straight line great-circle distance (in meters) between two points
 * using the Haversine formula. Excellent for local grouping metrics.
 */
export function getHaversineDistanceMeters(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number,
): number {
  const R = 6371000; // Radius of Earth in meters
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const rLat1 = (lat1 * Math.PI) / 180;
  const rLat2 = (lat2 * Math.PI) / 180;

  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(rLat1) * Math.cos(rLat2) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

  return R * c;
}

/**
 * 3. The Verification Agent
 * Cross-references a fresh incoming report coordinate with current unresolved entries.
 * Returns duplicate reference IDs in a 50m radius of identical category to consolidate clusters.
 *
 * @param newLat - Geolocation Latitude of new report
 * @param newLng - Geolocation Longitude of new report
 * @param category - Main target civic concern category
 * @param existingUnresolvedIssues - List of currently pending issues from the active system
 * @returns Object indicating if report is corroborated and the corresponding matching duplicate group ID if exists
 */
export function runVerificationAgent(
  newLat: number,
  newLng: number,
  category: CivicCategory,
  existingUnresolvedIssues: Array<{
    id: string;
    latitude: number;
    longitude: number;
    category: CivicCategory;
    corroboratedGroupId?: string;
  }>,
): {
  isCorroborated: boolean;
  corroboratedGroupId: string | null;
  targetIssueId: string | null;
} {
  const RAD_THRESHOLD_METERS = 50; // Strict standard as specified in critical requirements

  for (const issue of existingUnresolvedIssues) {
    // Check if category matches and issue is unresolved/active
    if (issue.category === category) {
      const distance = getHaversineDistanceMeters(
        newLat,
        newLng,
        issue.latitude,
        issue.longitude,
      );
      if (distance <= RAD_THRESHOLD_METERS) {
        // We found an active duplicate overlap in a 50m range!
        // Group them under a common verified Group ID, defaulting to the earliest report's ID
        const targetGroupId = issue.corroboratedGroupId || issue.id;
        return {
          isCorroborated: true,
          corroboratedGroupId: targetGroupId,
          targetIssueId: issue.id,
        };
      }
    }
  }

  return {
    isCorroborated: false,
    corroboratedGroupId: null,
    targetIssueId: null,
  };
}

/**
 * Priority Agent
 * Scores urgency into P1-P4 and determines SLA target.
 */
export function runPriorityAgent(
  severity: number,
  upvotes: number,
  category: string,
  isCorroborated: boolean,
): { priorityTier: "P1" | "P2" | "P3" | "P4"; slaTargetHours: number } {
  let score = severity * 2 + upvotes + (isCorroborated ? 5 : 0);
  if (
    category === "Water Leak" ||
    category === "Streetlight Out" ||
    category === "Pothole"
  )
    score += 5;

  if (score >= 25) return { priorityTier: "P1", slaTargetHours: 24 };
  if (score >= 18) return { priorityTier: "P2", slaTargetHours: 48 };
  if (score >= 10) return { priorityTier: "P3", slaTargetHours: 72 };
  return { priorityTier: "P4", slaTargetHours: 168 }; // 1 week
}

/**
 * Resolution Verification Agent
 * Compares before and after images to verify resolution.
 */
export async function runResolutionVerificationAgent(
  beforeImageBase64: string,
  afterImageBase64: string,
  mimeType: string,
  category: string,
): Promise<{ isResolved: boolean; confidence: number; notes: string }> {
  const ai = getAI();
  const cleanBefore = beforeImageBase64.replace(/^data:image\/\w+;base64,/, "");
  const cleanAfter = afterImageBase64.replace(/^data:image\/\w+;base64,/, "");

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        {
          inlineData: { data: cleanBefore, mimeType: mimeType || "image/jpeg" },
        },
        {
          inlineData: { data: cleanAfter, mimeType: mimeType || "image/jpeg" },
        },
        `You are the "Resolution-Verification Agent" for C.I.V.I.C. 
        Compare the first (before) and second (after) images for a reported ${category}. 
        Determine if the issue has been visibly resolved.`,
      ],
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            isResolved: {
              type: Type.BOOLEAN,
              description:
                "True if the issue appears resolved in the after image.",
            },
            confidence: {
              type: Type.INTEGER,
              description: "Confidence score from 0 to 100.",
            },
            notes: {
              type: Type.STRING,
              description:
                "Brief explanation of what was fixed or why it does not look fixed.",
            },
          },
          required: ["isResolved", "confidence", "notes"],
        },
      },
    });

    const parsedText = response.text;
    if (!parsedText) throw new Error("Gemini model yielded empty text reply.");

    return JSON.parse(parsedText) as {
      isResolved: boolean;
      confidence: number;
      notes: string;
    };
  } catch (err: any) {
    console.error("Resolution Verification Agent execution failure:", err);
    throw new Error(`AI Verification failed: ${err.message || err}`);
  }
}

/**
 * 4. Civic Assistant Chatbot Agent
 * Answers questions grounded in the user's report history and general civic guidance.
 */
export async function runChatbotAgent(
  message: string,
  history: Array<{ role: string; text: string }>,
  userIssuesContext: any[],
  language: string = "English",
): Promise<string> {
  const ai = getAI();
  try {
    const systemInstruction = `You are the C.I.V.I.C. Assistant, a helpful and polite virtual assistant for the city.
Respond in ${language}.
Here is the user's reporting history for context:
${JSON.stringify(userIssuesContext, null, 2)}
Answer the user's questions about their reports, how to report issues, or general civic questions. Keep answers concise, helpful, and friendly. Do not hallucinate report status.`;

    const contents = history.map((h) => ({
      role: h.role === "user" ? "user" : "model",
      parts: [{ text: h.text }],
    }));
    contents.push({ role: "user", parts: [{ text: message }] });

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: contents,
      config: {
        systemInstruction,
        temperature: 0.7,
      },
    });

    return response.text || "I am sorry, I could not generate a response.";
  } catch (err: any) {
    console.error("Chatbot Agent execution failure:", err);
    throw new Error(`Chatbot failed: ${err.message || err}`);
  }
}

/**
 * 5. Smart Description & Multilingual Agent
 * Generates a polished description from an image and optional voice note/text.
 */
export async function runSmartDescriptionAgent(
  imageBase64: string | null,
  imageMimeType: string | null,
  voiceBase64: string | null,
  voiceMimeType: string | null,
  language: string = "English",
): Promise<string> {
  const ai = getAI();
  try {
    const contents: any[] = [];

    if (imageBase64) {
      contents.push({
        inlineData: {
          data: imageBase64.replace(/^data:image\/\w+;base64,/, ""),
          mimeType: imageMimeType || "image/jpeg",
        },
      });
    }

    if (voiceBase64) {
      contents.push({
        inlineData: {
          data: voiceBase64.replace(
            /^data:(audio|video)\/\w+(;codecs=[^;]+)?;base64,/,
            "",
          ),
          mimeType: voiceMimeType || "audio/webm",
        },
      });
    }

    contents.push(`You are a Smart Description Agent for a civic reporting app.
Based on the provided image and/or audio voice note, write a clear, polite, and detailed description of the issue to be sent to city workers.
If audio is provided, use it as the primary context for what the user is reporting. Transcribe it and refine it.
Output ONLY the final description in ${language}. Keep it professional and under 3 sentences.`);

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: contents,
      config: {
        temperature: 0.3,
      },
    });

    return (
      response.text?.trim() || "Issue description generated from user report."
    );
  } catch (err: any) {
    console.error("Smart Description Agent execution failure:", err);
    throw new Error(`Smart Description failed: ${err.message || err}`);
  }
}

/**
 * 6. "My Impact" Story Agent
 * Generates a shareable summary of the user's contributions.
 */
export async function runPredictiveInsightAgent(
  issues: any[],
): Promise<
  {
    title: string;
    prediction: string;
    confidence: number;
    actionRecommended: string;
  }[]
> {
  const ai = getAI();
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        `You are the C.I.V.I.C. Predictive Insight Agent. 
        Analyze the following historical and current issue data to identify patterns, hotspots, and predict upcoming problems (e.g., "Ward 12 likely to see drainage issues this monsoon").
        Data:
        ${JSON.stringify(issues.map((i) => ({ c: i.category, s: i.severityScore, loc: i.locationName, d: i.description, stat: i.status })).slice(0, 100), null, 2)}
        
        Generate 2-3 predictive insights.`,
      ],
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              title: { type: Type.STRING },
              prediction: { type: Type.STRING },
              confidence: {
                type: Type.INTEGER,
                description: "Confidence percentage (0-100)",
              },
              actionRecommended: { type: Type.STRING },
            },
            required: [
              "title",
              "prediction",
              "confidence",
              "actionRecommended",
            ],
          },
        },
      },
    });

    const parsedText = response.text;
    if (!parsedText) throw new Error("Empty response");
    return JSON.parse(parsedText);
  } catch (err: any) {
    console.error("Predictive Insight Agent failure:", err);
    return [];
  }
}

export async function runDailyBriefingAgent(stats: any): Promise<string> {
  const ai = getAI();
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        `You are the C.I.V.I.C. Daily Briefing Agent. 
        Generate a concise, natural-language executive briefing for city staff.
        Stats for today:
        New Reports: ${stats.newReports}
        Resolved: ${stats.resolved}
        Trending Category: ${stats.trendingCategory}
        SLA Breaches: ${stats.slaBreaches}
        
        Output a 2-3 sentence engaging briefing.`,
      ],
      config: { temperature: 0.3 },
    });
    return response.text?.trim() || "Daily briefing unavailable.";
  } catch (err: any) {
    console.error("Daily Briefing Agent failure:", err);
    return "Daily briefing temporarily unavailable.";
  }
}

/**
 * 6. "My Impact" Story Agent
 * Generates a shareable summary of the user's contributions.
 */
export async function runImpactStoryAgent(
  stats: { reports: number; resolved: number; points: number },
  language: string = "English",
): Promise<{ title: string; story: string }> {
  const ai = getAI();
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        `You are the "My Impact" Agent. The user has reported ${stats.reports} issues, ${stats.resolved} of which are resolved, and earned ${stats.points} Impact Points.
        Write a short, engaging, gamified "Impact Story" card for them to share on social media.
        Make it inspiring, thanking them for being a Civic Hero.
        Language: ${language}.`,
      ],
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            title: {
              type: Type.STRING,
              description: "Catchy title for the story card.",
            },
            story: {
              type: Type.STRING,
              description: "A 2-3 sentence inspiring story paragraph.",
            },
          },
          required: ["title", "story"],
        },
      },
    });

    const parsedText = response.text;
    if (!parsedText) throw new Error("Gemini model yielded empty text reply.");

    return JSON.parse(parsedText) as { title: string; story: string };
  } catch (err: any) {
    console.error("Impact Story Agent execution failure:", err);
    throw new Error(`Impact Story failed: ${err.message || err}`);
  }
}
