/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GoogleGenAI, Type } from '@google/genai';
import { CivicCategory } from '../src/types';

// Initialize the standard Google GenAI SDK
// Respecting server-side safety constraints: loaded lazy on demand
let aiClient: GoogleGenAI | null = null;

/**
 * Lazy initializer for GoogleGenAI SDK to avoid module-load crashes.
 */
function getAI(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY environment variable is not defined.');
    }
    aiClient = new GoogleGenAI({ apiKey });
  }
  return aiClient;
}

/**
 * AI Response interface for Triage Agent.
 */
export interface TriageResponse {
  category: CivicCategory;
  severityScore: number;
  confidencePercentage: number;
  recommendedDepartment: string;
  autoGeneratedDescription: string;
}

/**
 * 1. The Triage Agent
 * Analyzes multimodal base64 image strings representing infrastructure issues
 * using Gemini Multimodal Structured Outputs.
 * 
 * @param imageBase64 - Base64 encoded string of user uploaded visual issue (with mime prefix stripped or intact)
 * @param mimeType - Image content-type (e.g., 'image/jpeg' or 'image/png')
 * @returns Precise structured AI civic triage analytics
 */
export async function runTriageAgent(imageBase64: string, mimeType: string): Promise<TriageResponse> {
  const ai = getAI();
  const cleanBase64 = imageBase64.replace(/^data:image\/\w+;base64,/, '');

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: [
        {
          inlineData: {
            data: cleanBase64,
            mimeType: mimeType || 'image/jpeg'
          }
        },
        'You are the "Triage Agent" of our C.I.V.I.C. platform, an autonomous civic triage specialist. ' +
        'Analyze this user-reported infrastructure issue picture. Assess the visual characteristics of the issue and provide structured diagnostic metrics.'
      ],
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            category: {
              type: Type.STRING,
              description: 'Type of infrastructure problem. Must fit categorisation: Pothole, Water Leak, Vandalism, Streetlight Out, Waste Issue, or Other.',
              enum: ['Pothole', 'Water Leak', 'Vandalism', 'Streetlight Out', 'Waste Issue', 'Other']
            },
            severityScore: {
              type: Type.INTEGER,
              description: 'Urgency / Severity of issue on a strict 1-10 scale (where 10 is immediate security critical hazard, 1 is cosmetic/local low priority issue).'
            },
            confidencePercentage: {
              type: Type.INTEGER,
              description: 'Mathematical confidence probability percentage of this categorization based on image resolution & clarity from 1 to 100.'
            },
            recommendedDepartment: {
              type: Type.STRING,
              description: 'Suggested Municipal agency or public authority best suited to dispatch repairs (e.g. Department of Transportation, Water & Sewage Authority, Department of Public Works, Parks & Forests).'
            },
            autoGeneratedDescription: {
              type: Type.STRING,
              description: 'Empathetic, clear, and highly detailed human-readable summary detailing the issue visual indicators and severity impacts for civil workers.'
            }
          },
          required: ['category', 'severityScore', 'confidencePercentage', 'recommendedDepartment', 'autoGeneratedDescription']
        }
      }
    });

    const parsedText = response.text;
    if (!parsedText) {
      throw new Error('Gemini model yielded empty text reply.');
    }
    
    return JSON.parse(parsedText) as TriageResponse;
  } catch (err: any) {
    console.error('Triage Agent execution failure:', err);
    throw new Error(`AI Triage failed: ${err.message || err}`);
  }
}

/**
 * 2. The Routing Agent
 * Interprets the structural findings output by the Triage Agent.
 * Applies internal service rules depending on confidence status of the model report.
 * 
 * @param triageResult - Structured outputs from CRM Triage assessment
 * @returns Status string categorising active routing channel
 */
export function runRoutingAgent(triageResult: TriageResponse): 'Auto-Routed' | 'Requires Human Verification' {
  // Rule: If model outputs high confidence (> 85%), route instantly. Otherwise, lock under human verification pipeline.
  if (triageResult.confidencePercentage >= 85) {
    return 'Auto-Routed';
  }
  return 'Requires Human Verification';
}

/**
 * Calculates straight line great-circle distance (in meters) between two points
 * using the Haversine formula. Excellent for local grouping metrics.
 */
export function getHaversineDistanceMeters(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371000; // Radius of Earth in meters
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const rLat1 = (lat1 * Math.PI) / 180;
  const rLat2 = (lat2 * Math.PI) / 180;

  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(rLat1) * Math.cos(rLat2) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

  return R * c;
}

/**
 * 3. The Verification Agent
 * Cross-references a fresh incoming report coordinate with current unresolved entries.
 * Returns duplicate reference IDs in a 50m radius of identical category to consolidate clusters.
 * 
 * @param newLat - Geolocation Latitude of new report
 * @param newLng - Geolocation Longitude of new report
 * @param category - Main target civic concern category
 * @param existingUnresolvedIssues - List of currently pending issues from the active system
 * @returns Object indicating if report is corroborated and the corresponding matching duplicate group ID if exists
 */
export function runVerificationAgent(
  newLat: number,
  newLng: number,
  category: CivicCategory,
  existingUnresolvedIssues: Array<{ id: string; latitude: number; longitude: number; category: CivicCategory; corroboratedGroupId?: string }>
): { isCorroborated: boolean; corroboratedGroupId: string | null } {
  const RAD_THRESHOLD_METERS = 50; // Strict standard as specified in critical requirements

  for (const issue of existingUnresolvedIssues) {
    // Check if category matches and issue is unresolved/active
    if (issue.category === category) {
      const distance = getHaversineDistanceMeters(newLat, newLng, issue.latitude, issue.longitude);
      if (distance <= RAD_THRESHOLD_METERS) {
        // We found an active duplicate overlap in a 50m range!
        // Group them under a common verified Group ID, defaulting to the earliest report's ID
        const targetGroupId = issue.corroboratedGroupId || issue.id;
        return {
          isCorroborated: true,
          corroboratedGroupId: targetGroupId
        };
      }
    }
  }

  return {
    isCorroborated: false,
    corroboratedGroupId: null
  };
}
