/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Supported civic issue categories.
 */
export type CivicCategory =
  | "Pothole"
  | "Water Leak"
  | "Vandalism"
  | "Streetlight Out"
  | "Waste Issue"
  | "Other";

/**
 * Status of reported civic issue.
 *
 * The original operational workflow states (Reported → … → Resolved) are kept
 * intact so the kanban board, staff list and resolution flow never break. The
 * Three-Layer Trust & Verification Engine adds the trust-track states that a new
 * submission flows through: a clean report enters "Pending Verification", is
 * promoted to "Community Verified" when an independent nearby report corroborates
 * it (Rule A) or to "Staff Verified" when municipal staff approve it (Rule B),
 * and is parked as "Flagged for Review" when Gemini forensics suspect fraud.
 */
export type CivicStatus =
  | "Reported"
  | "Auto-Routed"
  | "Requires Human Verification"
  | "Corroborated Report"
  | "In Progress"
  | "Resolved"
  // --- Trust & Verification Engine states ---
  | "Pending Verification"
  | "Community Verified"
  | "Staff Verified"
  | "Flagged for Review";

/**
 * How the citizen telemetry (Layer 1) sourced the map-pin coordinates.
 *  - "Historical-EXIF"  → embedded GPS EXIF from the original photo capture.
 *  - "Live-Fallback"    → the photo had no GPS EXIF, so we fell back to the
 *                         browser's live `navigator.geolocation`.
 */
export type MetadataMode = "Historical-EXIF" | "Live-Fallback";

/**
 * Structured diagnostics parsed by the Gemini Triage Agent.
 */
export interface TriageResult {
  category: CivicCategory;
  severityScore: number; // 1 to 10
  confidencePercentage: number; // 0 to 100
  recommendedDepartment: string;
  autoGeneratedDescription: string;
  urgencyReasoning?: string; // one-line justification of the severity/priority
  priorityTier?: "P1" | "P2" | "P3" | "P4";
  slaTargetHours?: number;
}

/**
 * Representation of a civic infrastructure issue in Firestore.
 */
export interface IssueComment {
  id: string;
  authorUid: string;
  authorName: string;
  text: string;
  createdAt: number;
}

/**
 * An AI-drafted petition attached to a high-impact issue. Citizens sign it
 * digitally (their uid is appended to `signatures`).
 */
export interface Petition {
  title: string;
  body: string;
  addressedTo: string;
  draftedAt: number;
  draftedByUid: string;
  signatures: string[];
}

export interface CivicIssue {
  id: string; // Document ID
  imageUrl: string; // Base64 or standard URL
  category: CivicCategory;
  severityScore: number;
  confidencePercentage: number;
  recommendedDepartment: string;
  description: string;
  latitude: number;
  longitude: number;
  address?: string;
  // Administrative geography (derived from reverse-geocode + ward→zone map).
  state?: string;
  city?: string;
  ward?: string;
  zone?: string;
  reportedByUid: string;
  reportedByName: string;
  reportedAt: number; // Timestamp
  status: CivicStatus;
  upvotesCount: number;
  upvotedBy?: string[];
  comments?: IssueComment[];
  isCorroborated: boolean;
  corroboratedGroupId?: string; // Links together duplicate/overlapping reports
  // --- Layer 1: Citizen telemetry (EXIF vs live geolocation) ---
  metadataMode?: MetadataMode; // how the pin coordinates were sourced
  captureTimestamp?: number; // EXIF DateTimeOriginal (ms epoch), when available
  metadataWarning?: boolean; // true when we fell back to live device location
  // --- Layer 2: Gemini cognitive forensics ---
  isAuthentic?: boolean; // forensics verdict: is the photo a genuine capture?
  fraudConfidenceScore?: number; // 0.0–1.0 likelihood the image is fraudulent
  visualEvidenceTags?: string[]; // e.g. ["pothole", "asphalt", "daylight"]
  // --- Layer 3: staff override audit trail (Rule B) ---
  verifiedByUid?: string; // staff uid who clicked "Corroborate & Approve"
  verifiedAt?: number; // timestamp of the staff approval
  verificationNotes?: string; // optional staff note on the approval
  priorityTier?: "P1" | "P2" | "P3" | "P4";
  slaTargetHours?: number;
  urgencyReasoning?: string; // AI one-line rationale for the priority tier
  duplicateCount?: number;
  petition?: Petition;
  // --- Auto-dispatch agent (Feature C) ---
  dispatchSummary?: string; // short record of the work-order sent to a department
  dispatchedAt?: number; // when a dispatch email was approved & sent
  dispatchedToName?: string; // department/official the work-order was addressed to
  // Hierarchy / workflow
  assignedToUid?: string; // field officer responsible
  escalationLevel?: 0 | 1 | 2; // 0 field, 1 zonal, 2 city
  resolvedImageUrl?: string;
  resolvedAt?: number;
  resolvedByUid?: string;
  resolutionConfidence?: number;
  resolutionNotes?: string;
}

/**
 * Indian municipal (ULB) staff hierarchy tiers.
 * field  → ward officer, scoped to one or more wards
 * zonal  → supervisor over a zone (group of wards)
 * city   → municipal commissioner, full access + manages the registry
 */
export type StaffTier = "field" | "zonal" | "city";

/**
 * A staff member entry in the `config/roles` registry document.
 */
export interface StaffMember {
  tier: StaffTier;
  wards?: string[]; // for field officers
  zone?: string; // for zonal supervisors
  displayName?: string;
}

/**
 * `config/roles` document — the single server-enforced source of staff truth.
 * Keyed by Firebase uid.
 */
export interface RolesConfig {
  staff: Record<string, StaffMember>;
}

/**
 * `config/wards` document — maps a ward name to its parent zone.
 */
export interface WardsConfig {
  wardToZone: Record<string, string>;
}

/**
 * Resolved permission scope for the signed-in user, derived from RolesConfig.
 */
export interface UserScope {
  role: "citizen" | "staff";
  tier?: StaffTier;
  wards: string[]; // wards this user may act on ([] for citizens / non-field)
  zone?: string;
}

/**
 * Representation of a user profile with gamified civic rank metrics.
 */
export interface CitizenProfile {
  uid: string;
  displayName: string;
  photoURL?: string;
  joinedAt: number;
  impactPoints: number; // 10 pts for reports, 50 pts if resolved by city
  civicRank: string; // e.g., 'Civic Novice', 'Neighbourhood Guardian', 'Urban Champion'
  reportsCount: number;
  role?: "citizen" | "staff";
  badges?: string[];
  ward?: string;
}

/**
 * Community Leaderboard leaderboard entry.
 */
export interface LeaderboardEntry {
  uid: string;
  displayName: string;
  impactPoints: number;
  civicRank: string;
  reportsCount: number;
  badges?: string[];
  ward?: string;
}
