/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Supported civic issue categories.
 */
export type CivicCategory =
  | "Pothole"
  | "Water Leak"
  | "Vandalism"
  | "Streetlight Out"
  | "Waste Issue"
  | "Other";

/**
 * Status of reported civic issue.
 */
export type CivicStatus =
  | "Reported"
  | "Auto-Routed"
  | "Requires Human Verification"
  | "Corroborated Report"
  | "In Progress"
  | "Resolved";

/**
 * Structured diagnostics parsed by the Gemini Triage Agent.
 */
export interface TriageResult {
  category: CivicCategory;
  severityScore: number; // 1 to 10
  confidencePercentage: number; // 0 to 100
  recommendedDepartment: string;
  autoGeneratedDescription: string;
  priorityTier?: "P1" | "P2" | "P3" | "P4";
  slaTargetHours?: number;
}

/**
 * Representation of a civic infrastructure issue in Firestore.
 */
export interface IssueComment {
  id: string;
  authorUid: string;
  authorName: string;
  text: string;
  createdAt: number;
}

export interface CivicIssue {
  id: string; // Document ID
  imageUrl: string; // Base64 or standard URL
  category: CivicCategory;
  severityScore: number;
  confidencePercentage: number;
  recommendedDepartment: string;
  description: string;
  latitude: number;
  longitude: number;
  address?: string;
  ward?: string;
  reportedByUid: string;
  reportedByName: string;
  reportedAt: number; // Timestamp
  status: CivicStatus;
  upvotesCount: number;
  upvotedBy?: string[];
  comments?: IssueComment[];
  isCorroborated: boolean;
  corroboratedGroupId?: string; // Links together duplicate/overlapping reports
  priorityTier?: "P1" | "P2" | "P3" | "P4";
  slaTargetHours?: number;
  duplicateCount?: number;
  resolvedImageUrl?: string;
  resolutionConfidence?: number;
  resolutionNotes?: string;
}

/**
 * Representation of a user profile with gamified civic rank metrics.
 */
export interface CitizenProfile {
  uid: string;
  displayName: string;
  photoURL?: string;
  joinedAt: number;
  impactPoints: number; // 10 pts for reports, 50 pts if resolved by city
  civicRank: string; // e.g., 'Civic Novice', 'Neighbourhood Guardian', 'Urban Champion'
  reportsCount: number;
  role?: "citizen" | "staff";
  badges?: string[];
  ward?: string;
}

/**
 * Community Leaderboard leaderboard entry.
 */
export interface LeaderboardEntry {
  uid: string;
  displayName: string;
  impactPoints: number;
  civicRank: string;
  reportsCount: number;
  badges?: string[];
  ward?: string;
}
